// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TabletopEvents.Api.Data;

#nullable disable

namespace TabletopEvents.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922202317_RenameEventRegistrationEventIdToEvent")]
    partial class RenameEventRegistrationEventIdToEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TabletopEvents.Api.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Format")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Game")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Format");

                    b.HasIndex("Game");

                    b.HasIndex("StartDateTime");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.EventRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Event")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Event");

                    b.ToTable("EventRegistrations", (string)null);
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Game")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Game");

                    b.ToTable("Formats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-0001-4000-8000-000000000001"),
                            Game = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "EDH"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0001-4000-8000-000000000002"),
                            Game = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Standard"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0001-4000-8000-000000000003"),
                            Game = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Modern"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0002-4000-8000-000000000001"),
                            Game = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Classic Constructed (CC)"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0002-4000-8000-000000000002"),
                            Game = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Blitz"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0003-4000-8000-000000000001"),
                            Game = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Core Constructed"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0003-4000-8000-000000000002"),
                            Game = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Infinity Constructed"
                        });
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Magic: The Gathering"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Flesh and Blood"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Lorcana"
                        });
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("Format")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Format");

                    b.ToTable("Templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b2b2b2-0001-4000-8000-000000000001"),
                            DefaultCapacity = 10,
                            DefaultDurationMinutes = 240,
                            Format = new Guid("a1a1a1a1-0001-4000-8000-000000000001"),
                            Name = "MTG - EDH"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0001-4000-8000-000000000002"),
                            DefaultCapacity = 30,
                            DefaultDurationMinutes = 300,
                            Format = new Guid("a1a1a1a1-0001-4000-8000-000000000002"),
                            Name = "MTG - Standard"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0002-4000-8000-000000000001"),
                            DefaultCapacity = 30,
                            DefaultDurationMinutes = 300,
                            Format = new Guid("a1a1a1a1-0002-4000-8000-000000000001"),
                            Name = "FAB - CC"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0003-4000-8000-000000000001"),
                            DefaultCapacity = 30,
                            DefaultDurationMinutes = 300,
                            Format = new Guid("a1a1a1a1-0003-4000-8000-000000000001"),
                            Name = "Lorcana - CC"
                        });
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.Event", b =>
                {
                    b.HasOne("TabletopEvents.Api.Models.Format", null)
                        .WithMany()
                        .HasForeignKey("Format")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabletopEvents.Api.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("Game")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.EventRegistration", b =>
                {
                    b.HasOne("TabletopEvents.Api.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("Event")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.Format", b =>
                {
                    b.HasOne("TabletopEvents.Api.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("Game")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TabletopEvents.Api.Models.Template", b =>
                {
                    b.HasOne("TabletopEvents.Api.Models.Format", null)
                        .WithMany()
                        .HasForeignKey("Format")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
